/** Centralised user-facing copy used across the authentication screens. */
export const STRINGS = {
  appName: 'DelhiveryHub',
  appTagline: 'Transport Management',

  welcomeBack: 'Welcome back',
  loginSubtitle: 'Sign in to manage your deliveries and operations.',
  email: 'Email',
  password: 'Password',
  firstName: 'First Name',
  lastName: 'Last Name',
  companyName: 'Company Name',
  phone: 'Phone Number',
  confirmPassword: 'Confirm Password',
  rememberMe: 'Remember me',
  forgotPassword: 'Forgot password?',
  login: 'Sign In',
  loggingIn: 'Signing in…',
  noAccount: 'No account yet?',
  createAccount: 'Create your account',
  registerSubtitle: 'Join DelhiveryHub to simplify your delivery management.',
  register: 'Create Account',
  registering: 'Creating account…',
  haveAccount: 'Already have an account?',
  loginNow: 'Sign in',
  agreeTo: 'I agree to the',
  terms: 'Terms & Conditions',
  andLabel: 'and',
  privacy: 'Privacy Policy',
  resetPassword: 'Reset Password',
  forgotSubtitle: 'Enter your registered email and we will send you a reset link.',
  sendResetLink: 'Send Reset Link',
  sendingReset: 'Sending…',
  resetLinkSentTitle: 'Check your inbox',

  // OTP Verification
  otpTitle: 'Verify Your Account',
  otpSubtitle: 'Enter the 6-digit code sent to your email.',
  otpPlaceholder: 'Enter 6-digit code',
  verifyOTP: 'Verify & Activate',
  verifyingOTP: 'Verifying…',
  resendOTP: 'Resend OTP',
  resendIn: 'Resend in',
  otpExpired: 'The OTP has expired. Please request a new one.',
  otpInvalid: 'Invalid OTP. Please try again.',
  maxAttemptsReached: 'Maximum attempts reached. Please request a new OTP.',
  resendOTPSuccess: 'A new OTP has been sent to your email.',

  // Account Status
  accountPending: 'Your account is waiting for administrator approval.',
  accountRejected: 'Your account has been rejected. Reason: ',
  accountApprovedOTP: 'Your account has been approved. Please enter the OTP sent to your email to activate your account.',
  accountActive: 'Welcome back!',

  // Role selection
  chooseRoleTitle: 'Choose how you want to use',
  chooseRoleBrand: 'DeliveryHub',
  staffRoleTitle: 'Staff',
  staffRoleSubtitle: 'Manage deliveries, assignments and fleet',
  adminRoleTitle: 'Admin',
  adminRoleSubtitle: 'Administration access',

  // Staff portal
  staffLoginTitle: 'Staff Login',
  staffSignupTitle: 'Staff Signup',
  adminLoginTitle: 'Admin Login',
  adminSignupTitle: 'Admin Signup',
  staffAccountPending:
    'Your Staff account is waiting for Admin approval. Please try again after your account has been approved.',
  staffAccountRejected: 'Your Staff account has been rejected. Please contact the administrator.',
  noStaffAccount: "Don't have a Staff account?",
  noAdminAccount: "Don't have an Admin account?",

  firstNamePlaceholder: 'Enter your first name',
  lastNamePlaceholder: 'Enter your last name',
  companyNamePlaceholder: 'Enter your company name',
  emailPlaceholder: 'you@company.com',
  phonePlaceholder: 'Enter your phone number',
  passwordPlaceholder: 'Create a password',
  confirmPasswordPlaceholder: 'Confirm your password',
} as const;