"""Local-disk file storage for uploaded slips/photos.

Implements the `STORAGE_BACKEND=local` path already scaffolded in
`core/config.py` (UPLOAD_DIR, MAX_UPLOAD_SIZE, ALLOWED_UPLOAD_TYPES) and the
`FileKind`/`StorageBackend` enums in `models/enums.py` — neither had an
actual implementation before. S3 is intentionally not implemented: no cloud
credentials or bucket exist in this project's configuration.
"""
from __future__ import annotations

import re
import uuid
from pathlib import Path

import aiofiles
from fastapi import UploadFile

from app.core.config import settings
from app.core.exceptions import ValidationBusinessError

_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9._-]+")

ALLOWED_SLIP_MIME_TYPES = {
    "image/jpeg",
    "image/jpg",
    "image/png",
    "image/webp",
    "application/pdf",
}


def _storage_root() -> Path:
    root = Path(settings.UPLOAD_DIR).resolve()
    root.mkdir(parents=True, exist_ok=True)
    return root


def _sanitize_filename(name: str) -> str:
    name = Path(name).name  # strip any directory components
    name = _SAFE_NAME_RE.sub("_", name)
    return name[-150:] or "file"


async def save_upload(file: UploadFile, subdir: str) -> tuple[str, int, str]:
    """Streams an uploaded file to disk under ``UPLOAD_DIR/subdir/``.

    Returns ``(relative_storage_path, size_bytes, mime_type)``. Raises
    ``ValidationBusinessError`` if the file is empty, too large, or not an
    allowed content type.
    """
    content_type = file.content_type or "application/octet-stream"
    if content_type not in ALLOWED_SLIP_MIME_TYPES:
        raise ValidationBusinessError(
            "Only JPG, PNG, WEBP, or PDF files are allowed for slip/photo uploads."
        )

    safe_name = _sanitize_filename(file.filename or "upload")
    relative_path = f"{subdir}/{uuid.uuid4()}_{safe_name}"
    absolute_path = _storage_root() / relative_path
    absolute_path.parent.mkdir(parents=True, exist_ok=True)

    size = 0
    max_size = settings.MAX_UPLOAD_SIZE
    async with aiofiles.open(absolute_path, "wb") as out:
        while chunk := await file.read(1024 * 1024):
            size += len(chunk)
            if size > max_size:
                await out.close()
                absolute_path.unlink(missing_ok=True)
                raise ValidationBusinessError(
                    f"File exceeds the maximum upload size of {max_size // (1024 * 1024)} MB."
                )
            await out.write(chunk)

    if size == 0:
        absolute_path.unlink(missing_ok=True)
        raise ValidationBusinessError("The uploaded file is empty.")

    return relative_path, size, content_type


async def save_generated_file(content: bytes, subdir: str, filename: str) -> tuple[str, int]:
    """Writes server-generated bytes (e.g. a CSV export) to disk. Unlike
    `save_upload`, there's no client-supplied MIME type to validate — the
    caller controls `filename`/content directly."""
    safe_name = _sanitize_filename(filename)
    relative_path = f"{subdir}/{uuid.uuid4()}_{safe_name}"
    absolute_path = _storage_root() / relative_path
    absolute_path.parent.mkdir(parents=True, exist_ok=True)
    async with aiofiles.open(absolute_path, "wb") as out:
        await out.write(content)
    return relative_path, len(content)


def resolve_absolute_path(relative_path: str) -> Path:
    """Resolves a stored relative path back to an absolute filesystem path.

    Rejects any path that would escape the storage root (defense against a
    maliciously crafted `storagePath`, though these are always
    server-generated via `save_upload` and never taken from client input).
    """
    root = _storage_root()
    candidate = (root / relative_path).resolve()
    if root not in candidate.parents and candidate != root:
        raise ValidationBusinessError("Invalid file path.")
    return candidate
