"""fix registration_status enum length

Revision ID: 47b951c17944
Revises: 002_super_admin_role
Create Date: 2026-08-07 15:28:57.121054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b951c17944'
down_revision: Union[str, Sequence[str], None] = '002_super_admin_role'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('approval_logs', 'action',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('pending', 'approved_pending_otp', 'completed', 'rejected', 'active', 'suspended', name='approval_action', native_enum=False),
               existing_nullable=False)
    op.alter_column('registration_requests', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('pending', 'approved_pending_otp', 'completed', 'rejected', 'active', 'suspended', name='registration_status', native_enum=False, length=30),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('pending', 'approved_pending_otp', 'completed', 'rejected', 'active', 'suspended', name='user_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('pending', 'approved_pending_otp', 'completed', 'rejected', 'active', 'suspended', name='user_status', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('registration_requests', 'status',
               existing_type=sa.Enum('pending', 'approved_pending_otp', 'completed', 'rejected', 'active', 'suspended', name='registration_status', native_enum=False, length=30),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('approval_logs', 'action',
               existing_type=sa.Enum('pending', 'approved_pending_otp', 'completed', 'rejected', 'active', 'suspended', name='approval_action', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
